/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _anmeldung_h_
#define _anmeldung_h_
//---------------------------------------------------------------------------------
extern const unsigned char anmeldung[];
extern const int anmeldung_size;
//---------------------------------------------------------------------------------
#endif //_anmeldung_h_
//---------------------------------------------------------------------------------
