/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _bild_ladebalken_h_
#define _bild_ladebalken_h_
//---------------------------------------------------------------------------------
extern const unsigned char bild_ladebalken[];
extern const int bild_ladebalken_size;
//---------------------------------------------------------------------------------
#endif //_bild_ladebalken_h_
//---------------------------------------------------------------------------------
