/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _bildMenueHintergrund_h_
#define _bildMenueHintergrund_h_
//---------------------------------------------------------------------------------
extern const unsigned char bildMenueHintergrund[];
extern const int bildMenueHintergrund_size;
//---------------------------------------------------------------------------------
#endif //_bildMenueHintergrund_h_
//---------------------------------------------------------------------------------
