/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _bild_button_h_
#define _bild_button_h_
//---------------------------------------------------------------------------------
extern const unsigned char bild_button[];
extern const int bild_button_size;
//---------------------------------------------------------------------------------
#endif //_bild_button_h_
//---------------------------------------------------------------------------------
