/*
  This file was autogenerated by raw2c.
Visit http://www.devkitpro.org
*/

//---------------------------------------------------------------------------------
#ifndef _logo_orbitalfrosch_h_
#define _logo_orbitalfrosch_h_
//---------------------------------------------------------------------------------
extern const unsigned char logo_orbitalfrosch[];
extern const int logo_orbitalfrosch_size;
//---------------------------------------------------------------------------------
#endif //_logo_orbitalfrosch_h_
//---------------------------------------------------------------------------------
